/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gate.access.control.gui;

/**
 *
 * @author TXG
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }
    
    public String strRole;
    
    public void mSetRoleRights()
    {
if(null!= strRole) 
{
switch (strRole) 
{ 
case "ADMIN": 
mnuLogoff.setEnabled(true); 
mnuExit.setEnabled(true); 
mnuUsers.setEnabled(true); 
mnuViewUsers.setEnabled(true); 
mnuVisitors.setEnabled (true);
mnuViewVisitors.setEnabled(true);
break; 
case "SUPERVISOR": 
mnuLogoff.setEnabled(true); 
mnuExit.setEnabled(true); 
mnuUsers.setEnabled(true); 
mnuViewUsers.setEnabled(true); 
mnuVisitors.setEnabled (true); 
mnuViewVisitors.setEnabled (true); 
break; 
case "STANDARD": 
mnuLogoff.setEnabled(true); 
mnuExit.setEnabled(true); 
mnuUsers.setEnabled(false); 
mnuViewUsers.setEnabled(true); 
mnuVisitors.setEnabled (false); 
mnuViewVisitors.setEnabled(true); 
break; 
default: 
break;
}
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpMain = new javax.swing.JDesktopPane();
        mnuMain = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuLogoff = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();
        mnuForms = new javax.swing.JMenu();
        mnuUsers = new javax.swing.JMenuItem();
        mnuViewUsers = new javax.swing.JMenuItem();
        mnuVisitors = new javax.swing.JMenuItem();
        mnuViewVisitors = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dpMainLayout = new javax.swing.GroupLayout(dpMain);
        dpMain.setLayout(dpMainLayout);
        dpMainLayout.setHorizontalGroup(
            dpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dpMainLayout.setVerticalGroup(
            dpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mnuFile.setText("File");

        mnuLogoff.setText("Logoff");
        mnuLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogoffActionPerformed(evt);
            }
        });
        mnuFile.add(mnuLogoff);

        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuExit);

        mnuMain.add(mnuFile);

        mnuForms.setText("Forms");

        mnuUsers.setText("Users");
        mnuUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsersActionPerformed(evt);
            }
        });
        mnuForms.add(mnuUsers);

        mnuViewUsers.setText("View Users");
        mnuViewUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuViewUsersActionPerformed(evt);
            }
        });
        mnuForms.add(mnuViewUsers);

        mnuVisitors.setText("Visitors");
        mnuVisitors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVisitorsActionPerformed(evt);
            }
        });
        mnuForms.add(mnuVisitors);

        mnuViewVisitors.setText("View Visitors");
        mnuViewVisitors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuViewVisitorsActionPerformed(evt);
            }
        });
        mnuForms.add(mnuViewVisitors);

        mnuMain.add(mnuForms);

        setJMenuBar(mnuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogoffActionPerformed
       frmLogin frmL = new frmLogin();
       frmL.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_mnuLogoffActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsersActionPerformed
      frmUsers frmU = new frmUsers();
      dpMain.add(frmU);
       frmU.setVisible(true);
    }//GEN-LAST:event_mnuUsersActionPerformed

    private void mnuViewUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuViewUsersActionPerformed
         frmViewUsers frmVU = new frmViewUsers();
      dpMain.add(frmVU);
       frmVU.setVisible(true);
    }//GEN-LAST:event_mnuViewUsersActionPerformed

    private void mnuVisitorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVisitorsActionPerformed
            frmVisitors frmV = new frmVisitors();
      dpMain.add(frmV);
       frmV.setVisible(true);
    }//GEN-LAST:event_mnuVisitorsActionPerformed

    private void mnuViewVisitorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuViewVisitorsActionPerformed
              frmViewVisitors frmVV = new frmViewVisitors();
      dpMain.add(frmVV);
       frmVV.setVisible(true);
    }//GEN-LAST:event_mnuViewVisitorsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpMain;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuForms;
    private javax.swing.JMenuItem mnuLogoff;
    private javax.swing.JMenuBar mnuMain;
    private javax.swing.JMenuItem mnuUsers;
    private javax.swing.JMenuItem mnuViewUsers;
    private javax.swing.JMenuItem mnuViewVisitors;
    private javax.swing.JMenuItem mnuVisitors;
    // End of variables declaration//GEN-END:variables
}
